### ISSUE TITLE
UnicodeDecodeError: ‘utf-8’ codec

### ISSUE THREAD

**Issue by AnabasisXu** [noword/MdxConverter#3]
UnicodeDecodeError: ‘utf-8’ codec can’t decode byte 0xd2 in position 52: invalid continuation byte
请教这个报错为什么在转化为html的时候不出现，但在转化为pdf的时候一定出现？

**Comment by noword** [comment]
请上传你的mdx和输入文本

**Comment by AnabasisXu** [comment]
好的。

您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/7dadf03dc74d40 或进入 cowtransfer.com 获取，在首页输入取件码：906332（24小时内有效）

前面是一大堆not found
WARNING: "wage" not found
         worker
WARNING: "worker" not found
Traceback (most recent call last):
  File "F:\Programs\Mdx\Converter\MdxConverter-master\MdxConverter.py", line 255, in <module>
    {
  File "F:\Programs\Mdx\Converter\MdxConverter-master\MdxConverter.py", line 221, in mdx2pdf
    mdx2html(mdx_name, input_name, TEMP_FILE, invalid_action, False)
  File "F:\Programs\Mdx\Converter\MdxConverter-master\MdxConverter.py", line 206, in mdx2html
    right_soup = merge_css(right_soup, os.path.split(mdx_name)[0], dictionary, with_toc)
  File "F:\Programs\Mdx\Converter\MdxConverter-master\MdxConverter.py", line 91, in merge_css
    css = get_css(soup, mdx_path, dictionary)
  File "F:\Programs\Mdx\Converter\MdxConverter-master\MdxConverter.py", line 77, in get_css
    css_name = soup.head.link["href"]
AttributeError: 'NoneType' object has no attribute 'link'

**Comment by abtxu** [comment]
没有变化。难道是我的系统设置出了问题吗？好像就我有这个问题。
https://forum.freemdict.com/t/topic/3886/45 帖子中，jns给出的改版，貌似现在不会报错了：
https://forum.freemdict.com/uploads/short-url/3Bwrzha0Iq9AM79Xta1fypn8vt3.py
