### ISSUE TITLE
coronavirus为什么无法识别？

### ISSUE THREAD

**Issue by ghost** [noword/MdxConverter#6]
Microsoft Windows [版本 10.0.17763.107]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>cd C:\Users\Administrator\Desktop\MdxConverter_v0.0.7L6mp3

C:\Users\Administrator\Desktop\MdxConverter_v0.0.7L6mp3>MdxConverter "LDOCE6++ En-Cn V2-19.mdx" "123.txt" "1.pdf"
基础词 Unit 22
         coronavirus
WARNING: "coronavirus" not found
Traceback (most recent call last):
  File "MdxConverter.py", line 275, in <module>
  File "MdxConverter.py", line 231, in mdx2pdf
  File "MdxConverter.py", line 215, in mdx2html
  File "MdxConverter.py", line 100, in merge_css
  File "MdxConverter.py", line 86, in get_css
AttributeError: 'NoneType' object has no attribute 'link'
[11528] Failed to execute script MdxConverter

C:\Users\Administrator\Desktop\MdxConverter_v0.0.7L6mp3>

**Comment by noword** [comment]
你的词典中没这个词
